/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas.proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;

/**
 *
 * @author dugla
 */
public class InterfazPrueba extends javax.swing.JFrame {
    

    /**
     * Creates new form InterfazPrueba
     */
    public InterfazPrueba() {
        initComponents();
        setLocationRelativeTo(null);// centrar mi interfaz
        inputArea.setEditable(false); // no puedo editar lo que hay dentro de mi text area
        Boton1.setEnabled(false); // no puedo darle al boton hasta que haya un metodo que me lo pueda acceder
    }
    
    
    
    //metodo para validar si el archivo seleccionado del jfilechooser cumple con el mismo formato que nos indica el proyecto
    private static boolean validarFormatoJson(String jsonString) {
        try {
            JSONObject jsonObject = new JSONObject(new JSONTokener(jsonString));
            for (String key : jsonObject.keySet()) {
                JSONArray metro = jsonObject.getJSONArray(key); // No validamos el nombre, solo la estructura
                for (int i = 0; i < metro.length(); i++) {
                    JSONObject line = metro.getJSONObject(i);
                    String lineName = line.keys().next();
                    JSONArray stops = line.getJSONArray(lineName);
                    for (int j = 0; j < stops.length(); j++) {
                        Object stop = stops.get(j);
                        if (stop instanceof JSONObject) {
                            // Validar formato de parada con nombre y conexión
                            JSONObject stopObj = (JSONObject) stop;
                            if (stopObj.keys().hasNext()) {
                                String from = stopObj.keys().next();
                                String to = stopObj.getString(from);
                                if (from.isEmpty() || to.isEmpty()) {
                                    return false;
                                }
                            } else {
                                return false;
                            }
                        } else if (!(stop instanceof String)) {
                            // Asegurarse de que sea una cadena si no es un objeto JSON
                            return false;
                        }
                    }
                }
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    
    // Define el filtro de archivos
    
    private static String getFileExtension(File file) {
        String name = file.getName();
        int lastIndex = name.lastIndexOf('.');
        if (lastIndex == -1) {
            return "";
        }
        return name.substring(lastIndex + 1);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputArea.setColumns(20);
        inputArea.setRows(5);
        jScrollPane1.setViewportView(inputArea);

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Boton1.setText("Siguiente");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Boton1))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //crea la variable para poder seleccionar mi archivo json
        JFileChooser fileChooser = new JFileChooser();

        // Define el filtro de archivos, o sea que desplega unas opciones que me acepten solo archivos de tipo jSon aunque eso puede cambiarse
        fileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                if (file.isDirectory()) {
                    return true;
                }
                String extension = getFileExtension(file);
                return extension.equals("json");
            }

            @Override
            public String getDescription() {
                return "Archivos JSON (*.json)";
            }
        });

        int result = fileChooser.showOpenDialog(rootPane);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String extension = getFileExtension(selectedFile);
            //validamos si el archivo seleccionado es de tipo json
            if (!extension.equals("json")) {
                JOptionPane.showMessageDialog(rootPane,
                        "Archivo no válido. Por favor, selecciona un archivo JSON.",
                        "Error de tipo de archivo",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                //ahora procedemos a leer ese archvi json correspondiente
                try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                    StringBuilder jsonContent = new StringBuilder();
                    String line;
                    while ((line = reader.readLine()) != null) {
                        jsonContent.append(line).append("\n");
                    }
                    JOptionPane.showMessageDialog(rootPane, "Archivo seleccionado correctamente");
                    Boton1.setEnabled(true); // ya podemos usar el boton para acceder a la siguiente accion
                    inputArea.setText(jsonContent.toString()); // escribimos nuestro json  previamente transformado a string en text area
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(rootPane, //caso si ocurre un error inesperado
                            "Error al leer el archivo: " + e.getMessage(),
                            "Error de lectura",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
        //creamos un string para obtener el archivo previamente escrito en el text area
        String traertexto = inputArea.getText();
        boolean Esvalido = validarFormatoJson(traertexto); // verificamos si sigue el formato que nos indica el proyecto de como tiene que ser el archivo json
        if (Esvalido) {
                JOptionPane.showMessageDialog(rootPane, "Formato válido");
                CargadorGrafo grafito = new CargadorGrafo(this);
                grafito.enviardatito(traertexto);// enviamos nuestro archivo para que se construya en la clase grafo y lo enviamos
                
                PanelPestanas pestanitas = new PanelPestanas(this);
                pestanitas.SetData(traertexto);
                
                Grafo grafo = CargadorGrafo.cargarGrafoDesdeJson(traertexto);
                pestanitas.GrafoInterfaz(grafo);
                
                pestanitas.setVisible(true);
                this.setVisible(false);
                
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Formato inválido. Revisa el contenido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_Boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JTextArea inputArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
